### ISSUE TITLE
查水表

### ISSUE THREAD

**Issue by TwilightKHQ** [hccluck/public_actions#16]
![image](https://user-images.githubusercontent.com/25874642/156726332-6f4af791-1129-4c21-9ce3-ebccb5ac32ca.png)

**Comment by hccluck** [comment]
什么情况，你这是被查到了？

**Comment by lanpangzhi** [comment]
+1

**Comment by ChengRanORZ** [comment]
+1

**Comment by TwilightKHQ** [comment]
> 
是的，开始查签到脚本了

**Comment by TwilightKHQ** [comment]
> 什么情况，你这是被查到了？

是的，我是前一天换了一个杯子，第二天就收到了这个通知

**Comment by thorn929** [comment]
我说定时任务签到咋不好使了

**Comment by thorn929** [comment]
> > 什么情况，你这是被查到了？
> 
> 是的，我是前一天换了一个杯子，第二天就收到了这个通知

哥们你的脚本好使吗？为啥我脚本一直在跑了， 签到确没成功，以前是好使的，cookie也是新的

**Comment by TwilightKHQ** [comment]
> 哥们你的脚本好使吗？为啥我脚本一直在跑了， 签到确没成功，以前是好使的，cookie也是新的

我是用的fork的，不是这个
