### ISSUE TITLE
使用方法请教？

### ISSUE THREAD

**Issue by zhoufanglu** [hccluck/public_actions#7]
使用方法：fork 本仓库

打开浏览器，登陆掘金，F12 查看 Network 面板，复制 cookie

打开 github 仓库的 Setting，选择 Secrets，新建下列 4 个仓库 Secret

以上三步我都做完了？请问脚本怎么跑起来呢？

**Comment by hccluck** [comment]
这个是定时跑的，每天早上5点半开始跑

**Comment by zhoufanglu** [comment]
> 这个是定时跑的，每天早上5点半开始跑

好的 谢谢，我只要fock到自己仓库， 不需要启动什么？

**Comment by zhoufanglu** [comment]
> 这个是定时跑的，每天早上5点半开始跑

今天看了 并没有自动签到
